"""adapters/cline/install.sh removes the skill-search row the old file-hook installer
(ADR-0051) merged into ~/.cline/data/settings/cline_mcp_settings.json (ADR-0086: the Agent
Plugin now provides that server), through adapters/lib/safe_write.py — a
symlinked settings file (a dotfiles-managed layout) must stay a symlink pointing at the same
real file, and a locked-down mode must not widen to the shell's umask. Same doctrine as every
other installer's own config write (ADR-0072); this is the per-call-site coverage Cline was
missing."""
import json
import os
import shutil
import subprocess
from pathlib import Path

from installer_env import installer_env

ROOT = Path(__file__).resolve().parents[1]
INSTALL_SH = ROOT / "adapters" / "cline" / "install.sh"


def _node_front(tmp_path):
    """installer_env's hermetic PATH deliberately omits `node`; Cline's own verify step shells
    out to it to load the plugin module, so add just that one (test_sibling_installers.py
    uses the same trick for its own Cline smoke test)."""
    front = tmp_path / "node-front"
    front.mkdir()
    node = shutil.which("node")
    if node:
        (front / "node").symlink_to(node)
    return front


def test_mcp_settings_write_keeps_a_symlink_and_its_mode(tmp_path):
    home = tmp_path / "home"
    settings_dir = home / ".cline" / "data" / "settings"
    settings_dir.mkdir(parents=True)
    settings = settings_dir / "cline_mcp_settings.json"
    old_row = {"command": "bash", "args": ["/old/checkout/bin/skill-search-mcp"]}
    settings.write_text(json.dumps({"mcpServers": {"other-server": {"command": "x"},
                                                   "skill-search": old_row}}))

    dotfiles = tmp_path / "dotfiles"
    dotfiles.mkdir()
    real = dotfiles / "cline_mcp_settings.json"
    shutil.move(str(settings), real)
    real.chmod(0o600)
    settings.symlink_to(real)

    env = installer_env(tmp_path, home, _node_front(tmp_path))
    r = subprocess.run(["bash", str(INSTALL_SH)], env=env, capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stdout + r.stderr

    assert settings.is_symlink(), "cline_mcp_settings.json must stay a symlink"
    assert os.path.realpath(settings) == str(real), \
        "the symlink must still point at the same dotfiles-managed file"
    data = json.loads(real.read_text())
    assert "skill-search" not in data["mcpServers"], "the old file-hook row must be retired"
    assert data["mcpServers"]["other-server"]["command"] == "x", \
        "an unrelated existing MCP server entry must survive the removal"
    assert oct(real.stat().st_mode & 0o777) == oct(0o600), "the real file must not widen past 0600"


def test_old_shims_are_retired_and_foreign_ones_kept(tmp_path):
    home = tmp_path / "home"
    hooks = home / ".cline" / "hooks"
    hooks.mkdir(parents=True)
    (hooks / "PostToolUse.cjs").write_text("// GENERATED by adapters/cline/install.sh\n")
    (hooks / "TaskStart.cjs").write_text("// the operator's own hook\n")
    env = installer_env(tmp_path, home, _node_front(tmp_path))
    r = subprocess.run(["bash", str(INSTALL_SH)], env=env, capture_output=True, text=True, timeout=120)
    assert r.returncode == 0, r.stdout + r.stderr
    assert not (hooks / "PostToolUse.cjs").exists(), "a shim the old installer wrote must be removed"
    assert (hooks / "TaskStart.cjs").exists(), "a hook the operator wrote must be left alone"
    assert (home / ".cline" / "plugins" / "skill-concierge.ts").is_file()


def test_invalid_settings_stop_the_install_before_anything_is_written(tmp_path):
    home = tmp_path / "home"
    settings_dir = home / ".cline" / "data" / "settings"
    settings_dir.mkdir(parents=True)
    (settings_dir / "cline_mcp_settings.json").write_text("{not json")
    env = installer_env(tmp_path, home, _node_front(tmp_path))
    r = subprocess.run(["bash", str(INSTALL_SH)], env=env, capture_output=True, text=True, timeout=120)
    assert r.returncode == 1, r.stdout + r.stderr
    assert "not valid JSON" in r.stderr
    assert not (home / ".cline" / "plugins" / "skill-concierge.ts").exists()
    assert not (home / ".agents" / "plugins" / "skill-concierge").exists()


def test_a_second_run_changes_nothing(tmp_path):
    home = tmp_path / "home"
    (home / ".cline").mkdir(parents=True)
    env = installer_env(tmp_path, home, _node_front(tmp_path))

    def snapshot():
        roots = (home / ".cline" / "plugins", home / ".agents" / "plugins")
        return {str(f): f.read_bytes() for r in roots for f in sorted(r.rglob("*")) if f.is_file()}

    for _ in range(2):
        r = subprocess.run(["bash", str(INSTALL_SH)], env=env, capture_output=True, text=True, timeout=120)
        assert r.returncode == 0, r.stdout + r.stderr
        if _ == 0:
            first = snapshot()
    assert first and snapshot() == first


def test_an_option_is_refused(tmp_path):
    home = tmp_path / "home"
    (home / ".cline").mkdir(parents=True)
    env = installer_env(tmp_path, home, _node_front(tmp_path))
    r = subprocess.run(["bash", str(INSTALL_SH), "--file-hooks"], env=env, capture_output=True, text=True,
                       timeout=120)
    assert r.returncode == 1 and "usage" in r.stderr
    assert not (home / ".cline" / "plugins").exists()
