#!/usr/bin/env node
/**
 * skill-concierge → Cline hook shim — PostToolUse (ADR-0051).
 * GENERATED by adapters/cline/install.sh — safe to regenerate; edits are lost.
 * Ledger capture only (use_skill / MCP search_skills / get_skill lanes);
 * always returns {cancel:false} — telemetry can never block a tool call.
 */
"use strict";
require("__SKILL_CONCIERGE_BRIDGE__")("tool_result");
