#!/usr/bin/env node
/**
 * skill-concierge → Cline hook shim — UserPromptSubmit (ADR-0051).
 * GENERATED by adapters/cline/install.sh — safe to regenerate; edits are lost.
 * Cline fires this alongside the operator's own UserPromptSubmit hook files and
 * merges the returned `contextModification` strings (hook-file-hooks.ts).
 */
"use strict";
require("__SKILL_CONCIERGE_BRIDGE__")("prompt_submit");
