#!/usr/bin/env bash
# skill-concierge — Cline installer (ADR-0086, supersedes ADR-0051's file-hook vehicle).
#
# Two native Cline plugin lanes, both loaded from THIS checkout:
#   1. Code plugin: writes the one-line loader ~/.cline/plugins/skill-concierge.ts, which
#      re-exports adapters/cline/skill-concierge.cline-plugin.ts (SKILL-FIRST rule, per-turn
#      enforcer menu, blocklist deny, ledger + exclusion echo). Cline discovers bare .ts files
#      in ~/.cline/plugins/ (it skips symlinks there, hence a generated file, not a link).
#   2. Agent Plugin (agent-plugins.org): adapters/cline/agent_plugin.py builds
#      ~/.agents/plugins/skill-concierge/ (plugin.json + mcp.json + skills/), which gives Cline
#      the skill-search MCP server and the plugin's own skills as skill-concierge:<name>. The
#      skills are generated copies because Cline rejects Claude Code's extra frontmatter keys;
#      the code plugin re-syncs them at every Cline session start.
# It also retires what the old file-hook installer left behind (its four marked shims in
# ~/.cline/hooks/ and its skill-search row in cline_mcp_settings.json), so a turn is never
# governed twice.
#
# Touches only skill-concierge-owned files. The loader and the Agent Plugin are rewritten in
# place; cline_mcp_settings.json is backed up before any change.
#   ./adapters/cline/install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLINE_DIR="$HOME/.cline"
CLINE_HOOKS="$CLINE_DIR/hooks"
CLINE_PLUGINS="$CLINE_DIR/plugins"
CLINE_SETTINGS="$CLINE_DIR/data/settings/cline_mcp_settings.json"
CLINE_SKILLS="$CLINE_DIR/data/settings/skills"
LOADER="$CLINE_PLUGINS/skill-concierge.ts"
AGENT_DIR="$HOME/.agents/plugins/skill-concierge"
AGENT_PLUGIN_PY="$ROOT/adapters/cline/agent_plugin.py"
PLUGIN_TS="$ROOT/adapters/cline/skill-concierge.cline-plugin.ts"
OLD_SHIMS="UserPromptSubmit PostToolUse TaskStart PreToolUse"
OLD_SHIM_MARK="GENERATED by adapters/cline/install.sh"
LOADER_MARK="GENERATED by skill-concierge adapters/cline/install.sh"

[ $# -eq 0 ] || { echo "usage: $0   (no options; the file-hook vehicle was removed in 0.63.0)" >&2; exit 1; }

echo "==> skill-concierge → Cline install (from: $ROOT)"
VERSION="$(python3 -c 'import json,sys;print(json.load(open(sys.argv[1]))["version"])' "$ROOT/.claude-plugin/plugin.json")"
echo "    SSOT version: $VERSION"
test -f "$PLUGIN_TS" || { echo "!! plugin missing: $PLUGIN_TS" >&2; exit 1; }

# Both ownership checks run before anything is written.
if [ -e "$LOADER" ] && ! grep -q "$LOADER_MARK" "$LOADER"; then
  echo "!! $LOADER exists and is not ours — refusing to overwrite it" >&2; exit 1
fi
if [ -e "$AGENT_DIR" ] && [ ! -f "$AGENT_DIR/.skill-concierge-managed.json" ]; then
  echo "!! $AGENT_DIR exists and was not built by this installer — refusing to replace it" >&2; exit 1
fi

# The old file-hook installer's skill-search row goes first: it is the one step that can
# refuse (invalid JSON), so a refusal stops the install before anything else is written.
PYTHONPATH="$SCRIPT_DIR/../lib" python3 "$SCRIPT_DIR/mcp_row.py" "$CLINE_SETTINGS"

# ── 1. Code plugin loader ────────────────────────────────────────────────────
mkdir -p "$CLINE_PLUGINS"
printf '// %s — loads the Cline plugin from this checkout.\n// Re-run that installer after moving the checkout. ADR-0086.\nexport { default, plugin } from %s;\n' \
  "$LOADER_MARK" "$(python3 -c 'import json,sys;print(json.dumps(sys.argv[1]))' "$PLUGIN_TS")" > "$LOADER"
echo "    plugin loader → $LOADER"

# ── 2. Agent Plugin (generated folder) ───────────────────────────────────────
python3 "$AGENT_PLUGIN_PY" sync "$AGENT_DIR"   # set -e: a refusal stops the install here

# ── 3. Retire the old file-hook vehicle's shims ──────────────────────────────
for evt in $OLD_SHIMS; do
  f="$CLINE_HOOKS/$evt.cjs"
  if [ -f "$f" ] && grep -q "$OLD_SHIM_MARK" "$f"; then
    rm -f "$f"; echo "    removed old file-hook shim: $f"
  fi
done

mkdir -p "$CLINE_SKILLS"

# ── Verify ───────────────────────────────────────────────────────────────────
echo "==> verify:"
NODE_NO_WARNINGS=1 node -e '
  import(process.argv[1]).then((m) => {
    const p = m.default;
    const ok = p && p.name === "skill-concierge" && typeof p.setup === "function"
      && ["beforeModel", "beforeTool", "afterTool"].every((h) => typeof p.hooks?.[h] === "function");
    console.log(ok ? "    plugin module loads: yes" : "    !! plugin module shape is wrong");
    process.exit(ok ? 0 : 1);
  }, (e) => { console.error("    !! plugin failed to load: " + e.message); process.exit(1); });
' "$LOADER"
python3 "$AGENT_PLUGIN_PY" check "$AGENT_DIR" >/dev/null \
  && echo "    Agent Plugin matches this checkout: $AGENT_DIR" \
  || { echo "    !! Agent Plugin out of date: $AGENT_DIR" >&2; exit 1; }
python3 "$ROOT/scripts/doctor.py" 2>/dev/null | grep -i "Cline integration" || true
echo "==> Done. Start a new Cline session (plugins and MCP servers load per session)."
echo "    Ledger rows land in ~/.claude/skill-concierge/logs/skill-invocation-ledger.log (harness=cline)."
